import Verso
import VersoManual
import VersoBlueprint
import BodyPinBlueprint.TeXPrelude
import BodyPinBlueprint.Bibliography
import BodyPinBlueprint.Bodies
import RB31EndToEnd.Linear.Vec3Twist
import RB31EndToEnd.NullCellule.Definitions
import RB31EndToEnd.NullCellule.PolynomialModel
import RB31EndToEnd.NullCellule.WittShear
import RB31EndToEnd.NullCellule.WittShearDistinctPrime
import RB31EndToEnd.NullCellule.SelectedNullHeight
import RB31EndToEnd.NullCellule.SelectedNullHeightPrimewise
import RB31EndToEnd.NullCellule.SelectedDirectionFibre
import RB31EndToEnd.NullCellule.SelectedDirectionHeight
import RB31EndToEnd.Algebra.PolynomialPrimeTrdegHeight
import RB31EndToEnd.Algebra.FiniteCoordinateTrdeg
import RB31EndToEnd.Algebra.LinearFormIdealHeight
import RB31EndToEnd.Algebra.MinimalPrimeLinearFibreHeight
import RB31EndToEnd.NullCellule.WeightInitialIdeal
import RB31EndToEnd.Algebra.FilteredInitialHeight

open Verso.Genre
open Verso.Genre.Manual
open Verso.Genre.Manual.InlineLean
open Informal

set_option doc.verso true

/-
# The Split-Klein isotropic-difference ideal

Paper §5, in the paper's order, together with Theorem 1.3: the paper states
that theorem in §1 and proves it at the end of §5, so its witness is the §1
statement, verbatim and contiguous, exactly as the flags chapter handles
Theorem 1.2.

Witness conventions are described in the leading comment of `Statement.lean`.
Two reconstructions particular to this chapter: the form and the ideal are
defined in running prose (§5's opening and the paragraph before Theorem 1.3),
so those witnesses wrap the paper's own sentences in a `definition`
environment.  No witness in this chapter joins separated pieces of the paper.
`check-witness-prose.py` reports 7 windows in this chapter; each was checked
and each is a text-layer artifact of one kind: a math token that survives as
a word in the text layer but not in a LaTeX transcription.
`isotropic_difference_ideal` (3) and `witt_shear_componentwise` (3) have
`Udist`, and `polynomial_dimension_formula` (1) has `trdegk` and `Frac` in
the display (5.5).  The other four witnesses match with no unmatched window.

Quoted bodies are named rather than copied; the mechanism is described in the
leading comment of `Statement.lean`.  Every `def` and `abbrev` a node here
names is quoted.  Several further definitions are quoted that no node names —
`Vec3.dot`, `edgePolynomial`, `InNullCellule`, `coefficientNullEquation`,
`IsInitialComponent` — because the nodes' statements are unreadable without
them.

Namespaces do not always match file names in the modules this chapter cites:
`LinearFormIdealHeight.lean` declares into `LinearFormIdeal`,
`MinimalPrimeLinearFibreHeight.lean` into `MinimalPrimeLinearFibre`,
and `FilteredInitialHeight.lean` partly into `NullCellulePolynomial`.

This chapter cannot stay inside the Mathlib-blanket-free part of the
formalization: the `NullCellule` and `Algebra` modules it documents reach the
blanket imports through `Vec3Twist.lean`.
-/

#doc (Manual) "The Split-Klein isotropic-difference ideal" =>

Section 5 of {Informal.citet "zheng2026"}[] translates the grounded
stress–codimension inequality of {bpref "grounded_model"}[the strata
chapter] — grounded meaning that a root vertex is fixed at the origin, so the
ambient dimension is $`3(|V| - 1)` — into commutative algebra. A twist $`X = (\omega, b)` is a point of the
six-dimensional space $`k^3 \oplus k^3`, and for a $`(2,2)`-sparse graph
$`F` on a vertex set with a chosen root the isotropic-difference ideal
$`I_F` is generated by one quadric per edge, the condition
$`q(X_u - X_v) = 0` that the difference of the two endpoint twists is
isotropic for the Split–Klein form $`q(\omega, b) = \omega \cdot b`.
Theorem 1.3 computes the height of every minimal prime of $`I_F` whose
component meets the _distinct locus_, the open set of twist tuples with
$`X_u \ne X_v` for all $`u \ne v`: the height is $`|E_F|`, so every such
component of the grounded variety has dimension $`6(|V| - 1) - |E_F|`. That
count enters the sufficiency direction through Proposition 6.5 of
{bpref "exceptional_pin_parameters"}[the assembly chapter], where the twist
differences across a partition come from pins. We state the form and the
ideal first, then the Witt shear that converts the quadrics into the linear
equations of the rigidity matrix, then the dimension formula for polynomial
rings, and then the height theorem; a closing section describes a weight and
initial-ideal apparatus that the formalization contains and nothing in the
final assembly uses.

The formalization proves the height theorem in a different ambient ring, and
the difference is global to this chapter, so we state it once. The paper
works over an arbitrary field $`k` that is infinite where Lemma 5.1 needs it;
the formalization fixes $`k = \Q` and leaves $`\R` and $`\C` to a
specialization step in the assembly. The paper indexes the generators of
$`I_F` by the edges of $`F`; the formalization indexes them by _selected
occurrences_ — for each edge of a chosen $`(2,2)`-sparse skeleton, one pin of
the body–pin graph joining that pair of blocks, with its orientation — so
that every equation retains which pin produced it. And the reachable
statements bound the height from below only; the paper's upper bound, from
Krull's height theorem, is not formalized, because the dimension count of
Proposition 6.5 uses only the lower bound.

:::group "splitklein_spine"
The paper's algebraic argument: the form, the ideal, the shear, the dimension
formula, and the height theorem.
:::

:::group "splitklein_infrastructure"
Weights and initial ideals, with no paper counterpart.
:::

# The Split-Klein form

:::definition "split_klein_form" (parent := "splitklein_spine") (lean := "RB31E2E.Twist.splitKlein") (tags := "paper")
The Split–Klein quadratic form on the six-dimensional twist space
$`k^3 \oplus k^3` is
$$`
q(\omega, b) = \omega \cdot b,
`
the bilinear dot product of the angular part against the translational part.
{Informal.citep "zheng2026" (kind := "equation") (index := "5.1")}[]
:::

```tex "split_klein_form"
\begin{definition}
On the six-dimensional vector space $k^3 \oplus k^3$, define the Split--Klein
quadratic form
\begin{equation}
  q(\omega, b) = \omega \cdot b.
  \tag{5.1}
\end{equation}
\end{definition}
```

The form is hyperbolic of signature $`(3,3)` over $`\R`, though the paper
uses no signature property: what the arguments use is that $`q` vanishes on
the twist differences of pinned pairs, which is
{bpref "pin_fibre"}[Lemma 6.2 of the necessity chapter], and that a skew
shear preserves it exactly, which is the next lemma. In the formalization
the form is one line over any commutative ring, on the twist type of
{bpref "twist_system"}[the necessity chapter], and the dot product is the
bilinear coordinate sum rather than a Hermitian product:

```BodyPinBlueprint.bodies
RB31E2E.Vec3.dot
RB31E2E.Twist.splitKlein
```

# The ideal and the distinct locus

:::definition "isotropic_difference_ideal" (parent := "splitklein_spine") (lean := "RB31E2E.NullCellulePolynomial.edgeIdeal, RB31E2E.SelectedNullHeight.coefficientSelectedNullIdeal") (tags := "paper, deviation") (uses := "split_klein_form, sparse22")
Fix a root $`o \in V` and set $`X_o = 0`. In the polynomial ring
$`R = k[\omega_{v,i}, b_{v,i} : v \ne o,\ 1 \le i \le 3]`, the Split–Klein
isotropic difference ideal of a simple graph $`F = (V, E_F)` is
$$`
I_F = \bigl(f_{uv} : uv \in E_F\bigr), \qquad
f_{uv} = q(X_u - X_v) = (\omega_u - \omega_v) \cdot (b_u - b_v),
`
and the distinct locus $`U_{\mathrm{dist}} \subseteq \operatorname{Spec} R`
is the open complement of the diagonal closed subsets
$`\{X_u = X_v\}` over the pairs $`u \ne v`.
{Informal.citep "zheng2026" (kind := "equation") (index := "1.6 and 5.2")}[]
:::

```tex "isotropic_difference_ideal"
\begin{definition}
Fix a nonempty finite vertex set $V$ and a root vertex $o$, and set
$n_0 = |V| - 1$.  For $v \ne o$, introduce $\omega_v, b_v \in k^3$, and set
$\omega_o = b_o = 0$.  For a finite simple $(2,2)$-sparse graph
$F = (V, E_F)$, write $m = |E_F|$ and consider the polynomial ring
\[
  R = k[\omega_{v,i}, b_{v,i} : v \ne o, 1 \le i \le 3]
\]
and the Split--Klein isotropic difference ideal
\begin{equation}
  I_F = \bigl(f_{uv} : uv \in E_F\bigr), \qquad
  f_{uv} = q(X_u - X_v) = (\omega_u - \omega_v) \cdot (b_u - b_v).
  \tag{5.2}
\end{equation}
Let
\[
  U_{\mathrm{dist}} = \{X_u \ne X_v \text{ for all } u \ne v\}
    \subseteq \operatorname{Spec} R.
\]
This is the complement in $\operatorname{Spec} R$ of the union of the
diagonal closed subsets, and is therefore open.
\end{definition}
```

The formalization contains two builds of this ideal, and only one of them is
used by the root theorem; the deviation register has the entry. The literal
build, in `PolynomialModel.lean`, takes six variables at _every_
vertex, spans the ideal by one orientation-independent quadric per edge, and
proves that its zero locus is exactly the null-difference condition on twist
assignments; the module family's own name for the pair of conditions —
pairwise distinct, and null on every selected edge — is the _null cellule_,
a name this blueprint has not checked against a primary source.

```BodyPinBlueprint.bodies
RB31E2E.InNullCellule
RB31E2E.NullCellulePolynomial.edgePolynomial
RB31E2E.NullCellulePolynomial.edgeIdeal
```

The build the assembly uses is grounded and provenance-labelled. Its ambient
ring has six variables per non-root vertex over $`\Q`, exactly the paper's
$`R` with $`k = \Q`; the root twist is the constant zero rather than a
variable, so grounding is a property of the ring and never has to be imposed
on an ideal. Each generator is the Split–Klein quadric of the relative twist
across one selected pin occurrence:

```BodyPinBlueprint.bodies
RB31E2E.SelectedNullHeight.coefficientNullEquation
RB31E2E.SelectedNullHeight.coefficientSelectedNullIdeal
```

The distinct locus is likewise handled by element rather than by open set:
for each ordered pair of distinct vertices a _distinctness chart_ picks one
of the six coordinates of the twist difference, the product of the chosen
coordinates over all pairs is a single denominator polynomial, and "the
component of $`P` meets $`U_{\mathrm{dist}}`" is the condition that this
denominator not lie in $`P`. On such a component
{name RB31E2E.WittShearDistinctPrime.mapped_pairDifference_ne_zero}`mapped_pairDifference_ne_zero`
shows every pairwise twist difference is nonzero in the function field
$`\operatorname{Frac}(R/P)`, which is the form of "meets the open set" used
in the proofs.

# The componentwise Witt shear

The height computation needs pairwise distinct _three-dimensional_
coordinates, because the grounded inequality (4.7) applies to configurations
in $`K^3`, while on a component of $`V(I_F)` only the _six-dimensional_
twists are pairwise distinct: the translational parts $`b_v` may coincide.
The shear repairs this without moving the ideal.

:::lemma_ "witt_shear_componentwise" (parent := "splitklein_spine") (lean := "RB31E2E.WittShear.shear, RB31E2E.WittShear.splitKlein_shear, RB31E2E.WittShear.exists_common_base_shear_snd_ne_zero") (tags := "paper") (uses := "isotropic_difference_ideal")
Let $`Z \subseteq V(I_F)` be an irreducible component meeting
$`U_{\mathrm{dist}}`. There is a constant skew-symmetric matrix
$`S_Z \in \mathfrak{so}_3(k)` such that $`a_v := b_v + S_Z \omega_v`
satisfies $`a_u - a_v \ne 0` in $`k(Z)` for every $`u \ne v`, and the linear
automorphism $`\Phi_{S_Z} : (\omega, b) \mapsto (\omega, b + S_Z \omega)`
fixes every generator of $`I_F`.
{Informal.citep "zheng2026" (kind := "lemma") (index := "5.1")}[]
:::

```tex "witt_shear_componentwise"
\begin{lemma}[A componentwise Witt shear]
Let $Z \subseteq V(I_F)$ be an irreducible component meeting
$U_{\mathrm{dist}}$.  There is a constant skew-symmetric matrix
$S_Z \in \mathfrak{so}_3(k)$ such that, in $k(Z)$,
\begin{equation}
  a_v := b_v + S_Z \omega_v
  \tag{5.3}
\end{equation}
satisfies $a_u - a_v \ne 0$ for every $u \ne v$.  In the new coordinates
$a = b + S_Z \omega$, the linear automorphism
\begin{equation}
  \Phi_{S_Z} : (\omega, b) \longmapsto (\omega, b + S_Z \omega)
  \tag{5.4}
\end{equation}
satisfies $f_{uv} \circ \Phi_{S_Z} = f_{uv}$, and hence fixes every
generator of $I_F$.
\end{lemma}
```

:::proof "witt_shear_componentwise"
The intersection $`Z \cap U_{\mathrm{dist}}` is dense in $`Z`, so every
difference vector $`(\omega_u - \omega_v, b_u - b_v)` is nonzero in
$`k(Z)^6`. For a fixed pair $`u \ne v`, the matrices $`S \in
\mathfrak{so}_3(k)` with $`(b_u - b_v) + S(\omega_u - \omega_v) = 0` form an
affine subspace, and it is proper: were it all of $`\mathfrak{so}_3(k)`,
taking $`S = 0` would give $`b_u = b_v` and the three elementary skew
matrices would give $`\omega_u = \omega_v`, contradicting distinctness. A
finite-dimensional affine space over an infinite field is not a union of
finitely many proper affine subspaces, so some $`S_Z` avoids the subspaces
of all pairs. Finally $`x^T S_Z x = 0` holds for a skew matrix over every
extension field, with $`x = \omega_u - \omega_v`, so each generator
$`f_{uv}` is fixed, and $`\Phi_{-S_Z}` inverts $`\Phi_{S_Z}`.
:::

Example 5.2 of {Informal.citet "zheng2026"}[] illustrates the choice on one
coincident pair: if $`\omega_u - \omega_v = e_3` and $`b_u = b_v`, the shear
with $`S x = e_1 \times x` moves the difference of the new coordinates to
$`-e_2 \ne 0` while $`x \cdot S x = 0` keeps the form.

The formal shear is written with the cross product: for a parameter vector
$`s \in k^3` the map takes $`(\omega, b)` to $`(\omega, b + \omega \times
s)`, which is the paper's $`\Phi_S` for the skew matrix $`S x = x \times s`,
and every skew $`3 \times 3` matrix arises this way.

```BodyPinBlueprint.bodies
RB31E2E.WittShear.shear
```

{name RB31E2E.WittShear.splitKlein_shear}`splitKlein_shear` is the exact
invariance of the form, and
{name RB31E2E.WittShear.algEquiv}`algEquiv` is the induced automorphism of
the polynomial ring, under which
{name RB31E2E.WittShearDistinctPrime.map_coefficientSelectedNullIdeal_algEquiv}`map_coefficientSelectedNullIdeal_algEquiv`
shows the selected-null ideal is literally invariant. The existence half is
{name RB31E2E.WittShear.exists_common_base_shear_snd_ne_zero}`exists_common_base_shear_snd_ne_zero`:
one parameter drawn from the infinite base field makes the translational
half of every member of a finite family of nonzero twists nonzero at once.
Its avoidance argument differs from the paper's in one respect: instead of
choosing a point outside finitely many proper affine subspaces of
$`\mathfrak{so}_3`, the formal proof restricts the parameter to the moment
curve $`r \mapsto (r, r^2, r^3)`, where each pair's failure locus becomes
the root set of a nonzero univariate polynomial, and
{name RB31E2E.WittShear.exists_base_eval_ne_zero}`exists_base_eval_ne_zero`
finds a rational point avoiding the product. A table correction from this
chapter: the declaration previously named on this node,
{name RB31E2E.WittShear.exists_scalar_shear_snd_ne_zero}`exists_scalar_shear_snd_ne_zero`,
states a one-twist version with a coordinate-axis parameter, and nothing in
the development calls it.

# The dimension formula

:::lemma_ "polynomial_dimension_formula" (parent := "splitklein_spine") (lean := "RB31E2E.PolynomialPrimeTrdegHeight.polynomialPrime_height_add_fractionTrdeg_eq_natCard") (tags := "paper")
Let $`A = k[x_1, \dots, x_N]` and let $`P \subset A` be a prime ideal. Then
$$`
\operatorname{ht} P + \trdeg_k \operatorname{Frac}(A/P) = N.
`
{Informal.citep "zheng2026" (kind := "lemma") (index := "5.3")}[]
:::

```tex "polynomial_dimension_formula"
\begin{lemma}[The dimension formula for a polynomial ring]
Let $A = k[x_1, \ldots, x_N]$, and let $P \subset A$ be a prime ideal.  Then
\begin{equation}
  \operatorname{ht} P + \operatorname{trdeg}_k \operatorname{Frac}(A/P) = N.
  \tag{5.5}
\end{equation}
\end{lemma}
```

The paper's proof is a citation, to the dimension theory of
{Informal.citet "eisenbud1995"}[] via Noether normalization. The
formalization proves the formula from scratch, since Mathlib does not
currently carry it: a transcendence basis is extracted from the coordinates
themselves, the height of a maximal ideal is computed from the Jacobson
property of finite polynomial rings, and no catenarity assumption enters.
The companion lemmas of
{name RB31E2E.FiniteCoordinateTrdeg.trdeg_le_card_of_adjoin_range_eq_top}`FiniteCoordinateTrdeg`
give the coordinate-generation bound $`\trdeg_k K \le 3|V|` that the
semismallness statements of {bpref "stress_codim_flags"}[the flags chapter]
are phrased with.

# The height theorem

:::theorem "isotropic_ideal_height" (parent := "splitklein_spine") (lean := "RB31E2E.SelectedDirectionHeight.splitMinimalPrime_height_ge_edgeCard_of_groundedPF, RB31E2E.SelectedNullHeightPrimewise.incidenceLocalizedSelectedNullIdealHeight_ge_selectedCard_of_groundedPF") (tags := "paper, deviation") (uses := "isotropic_difference_ideal")
Let $`V \ne \emptyset` and let $`F` be a finite simple $`(2,2)`-sparse graph
on $`V`. If $`P` is a minimal prime of $`I_F` whose component $`V(P)` meets
the distinct locus, then $`\operatorname{ht} P = |E_F|`; equivalently, with
$`X_o = 0`, every component meeting the distinct locus has dimension
$`6(|V| - 1) - |E_F|`.
{Informal.citep "zheng2026" (kind := "theorem") (index := "1.3")}[]
:::

```tex "isotropic_ideal_height"
\begin{theorem}[Height of the distinct isotropic-difference ideal]
Let $V \ne \emptyset$, and let $F$ be a finite simple $(2,2)$-sparse graph
on $V$.  If $P$ is a minimal prime of $I_F$ and the irreducible component
$V(P)$ meets the open set
\[
  \{(X_v)_{v \in V} : X_u - X_v \ne 0 \text{ for all } u \ne v\}
\]
then
\[
  \operatorname{ht} P = |E_F|.
\]
Equivalently, after fixing $X_o = 0$, every irreducible component that meets
the distinct locus has dimension
\begin{equation}
  6(|V| - 1) - |E_F|.
  \tag{1.7}
\end{equation}
\end{theorem}
```

:::proof "isotropic_ideal_height" (uses := "witt_shear_componentwise, polynomial_dimension_formula, grounded_model")
Fix the minimal prime $`P` and its component $`Z = V(P)`. First apply the
Witt shear of $`Z`: the coordinate change $`a = b + S_Z \omega` preserves
every generator, so it takes $`P` to a minimal prime $`P'` of $`I_F` of the
same height, and the configuration $`a` is pairwise distinct in
$`\operatorname{Frac}(R/P')`. Second, contract to the coefficient ring:
write $`R \cong A[\omega]` with $`A = k[a_{v,i} : v \ne o]`, set
$`\mathfrak{p} = P' \cap A` and $`K = \operatorname{Frac}(A/\mathfrak{p})`,
so that $`K` is generated by the coordinates of $`a` and the configuration
stays pairwise distinct in $`K^3`. With
$`s = \dim_K \ker D_F(a)^T` and $`r = \operatorname{rank}_K D_F(a)`, the
matrix has $`m` rows, so $`r + s = m`; the dimension formula gives
$`\operatorname{ht} \mathfrak{p} + \trdeg_k K = 3n_0`, and the grounded
inequality (4.7) gives $`s + \trdeg_k K \le 3n_0`, so
$`s \le \operatorname{ht} \mathfrak{p}`. Third, pass to the generic fibre
over $`K`: substituting $`y = \omega` in the motion equations shows the
fibre of $`P'` is the prime linear ideal $`L_F` generated by the rows of
$`D_{F,o}(a)`, of height $`r`, and minimality of $`P'` forces the fibre to
equal $`L_F`. The relative height equality for
$`\mathfrak{p} \subseteq P'` then gives
$$`
\operatorname{ht} P' = \operatorname{ht} \mathfrak{p} +
\operatorname{ht} L_F \ge s + r = m,
`
while $`P'` is a minimal prime of an ideal with $`m` generators, so Krull's
height theorem gives $`\operatorname{ht} P' \le m`.
:::

The formal route has the same three steps, with the lower bound as its only
conclusion. The shear step is
{name RB31E2E.WittShearDistinctPrime.exists_splitMinimalPrime_with_injective_placement}`exists_splitMinimalPrime_with_injective_placement`:
one rational shear parameter, produced by the common-shear lemma applied to
the pairwise differences in the function field, turns $`P` into an
equal-height minimal prime whose induced placement
$`a : V \to K^3` is injective. The contraction and fibre steps run through
the angular/translational split of the ambient ring recorded on
{bpref "grounded_model"}[the grounded-model node]:
{name RB31E2E.SelectedDirectionFibre.splitSelectedNullIdeal_eq_linearFormIdealOver}`splitSelectedNullIdeal_eq_linearFormIdealOver`
identifies the transported ideal with the linear-form ideal of the grounded
direction rows — the paper's $`L_F` — over the translational coefficient
ring;
{name RB31E2E.MinimalPrimeLinearFibre.polynomialPrime_height_eq_contractionHeight_add_fractionFibreHeight}`polynomialPrime_height_eq_contractionHeight_add_fractionFibreHeight`
is the relative height equality
$`\operatorname{ht} P' = \operatorname{ht} \mathfrak{p} + \operatorname{ht} L_F`;
{name RB31E2E.LinearFormIdeal.finrank_span_le_linearFormIdeal_height}`finrank_span_le_linearFormIdeal_height`
bounds $`\operatorname{ht} L_F` below by the rank $`r`; the grounded
inequality, supplied as the semismallness hypothesis, bounds
$`\operatorname{ht} \mathfrak{p}` below by $`s`; and rank–nullity closes
with $`s + r = |E_F|`. The composite is
{name RB31E2E.SelectedDirectionHeight.splitMinimalPrime_height_ge_edgeCard_of_groundedPF}`splitMinimalPrime_height_ge_edgeCard_of_groundedPF`,
and
{name RB31E2E.SelectedNullHeightPrimewise.incidenceLocalizedSelectedNullIdealHeight_ge_selectedCard_of_groundedPF}`incidenceLocalizedSelectedNullIdealHeight_ge_selectedCard_of_groundedPF`
transports the bound through the two localizations and the adjunction of the
retained pin variables into the form the assembly of
{bpref "exceptional_pin_parameters"}[the next chapter] reads. The equality
of Theorem 1.3 is not formalized: no reachable statement carries the Krull
upper bound $`\operatorname{ht} P \le m`, because the dimension count of
Proposition 6.5 needs only $`\operatorname{ht} P \ge |E_F|`. The register
records both this and the change of ambient ring.

# The ungrounded variety

:::corollary "ungrounded_variety" (parent := "splitklein_spine") (tags := "paper, deviation") (uses := "isotropic_ideal_height")
Let $`F` be a finite simple $`(2,2)`-sparse graph on $`t \ge 1` vertices. On
the locus of pairwise distinct twist tuples $`(X_i)_i` with all six
coordinates of every vertex as variables, every irreducible component of the
variety cut out by $`q(X_i - X_j) = 0` over the edges $`ij \in E_F` has
dimension at most $`6t - |E_F|`; after fixing the value at one vertex, at
most $`6(t-1) - |E_F|`.
{Informal.citep "zheng2026" (kind := "corollary") (index := "5.4")}[]
:::

```tex "ungrounded_variety"
\begin{corollary}[The ungrounded isotropic-difference variety]
Let $F = (V, E_F)$ be a finite simple $(2,2)$-sparse graph on $t \ge 1$
vertices, with a specified root vertex $o$.  On the open set on which
$X_i - X_j \ne 0$ for every distinct pair, with
$X_i = (\omega_i, b_i) \in k^3 \oplus k^3$, every irreducible component of
the variety defined by
\begin{equation}
  (\omega_i - \omega_j) \cdot (b_i - b_j) = 0 \qquad (ij \in E_F)
  \tag{5.11}
\end{equation}
has dimension at most $6t - |E_F|$.  After fixing the value at one vertex,
the dimension is at most $6(t - 1) - |E_F|$.
\end{corollary}
```

The paper's proof is a product decomposition: under the linear change of
coordinates $`(X_i)_i \mapsto (X_o, (X_i - X_o)_{i \ne o})` every equation
depends only on the differences, so the ungrounded variety is the product of
the six-dimensional common-translation space with the grounded one, and the
claim follows from Theorem 1.3. Neither the ungrounded variety nor the
product decomposition has a Lean counterpart, and the register has the
entry: the formalization is grounded from the ring onward, so the grounded
clause of the corollary is the height theorem above, and the assembly of
{bpref "exceptional_pin_parameters"}[the next chapter] invokes that clause
directly.

# Weights and initial ideals

:::lemma_ "lean_weight_apparatus" (parent := "splitklein_infrastructure") (lean := "RB31E2E.NullCellulePolynomial.weightInitialIdeal, RB31E2E.NullCellulePolynomial.WeightInitialHeightMonotone") (tags := "lean-only") (uses := "isotropic_difference_ideal") (uses_intent := "technical")
Provenance weights on the twist variables, the minimum-weight initial
component of a polynomial, the resulting weight-initial ideal, and exact
weight-layer decompositions of the replaced equations for an edge-to-$`K_3`
and a vertex-to-$`K_4` move. A height-comparison interface between an ideal
and its weight-initial ideal is stated as a proposition and neither assumed
nor proved anywhere in the development.
:::

Four `NullCellule` modules and part of a fifth develop a degeneration
apparatus with no paper counterpart: variables are weighted by provenance,
the minimum nonzero weighted-homogeneous component of a polynomial is
singled out, and for two replacement moves — an edge replaced by a
$`K_3` and a vertex replaced by a $`K_4` — the exact weight-zero, -one and
-two layers of every replaced Split–Klein equation are computed, over
$`\Q`, together with the identity that the weight-zero layer of a replaced
equation is the original equation.

```BodyPinBlueprint.bodies
RB31E2E.NullCellulePolynomial.IsInitialComponent
RB31E2E.NullCellulePolynomial.weightInitialIdeal
RB31E2E.NullCellulePolynomial.WeightInitialHeightMonotone
```

The last quoted definition is the reason the apparatus ends where it does.
`FilteredInitialHeight.lean` states the height comparison
$`\operatorname{ht}(\operatorname{in}_w I) \le \operatorname{ht} I` as a
named proposition and proves the parts of the bridge that follow from the
graded decomposition alone; its own comment records that Mathlib's Rees
algebra currently covers powers of a single ideal and not the flat
one-parameter family of an arbitrary weight filtration, and the proposition
is never assumed and never discharged. None of the weight modules is
reachable from the root theorem — 157 declarations across the four pure
weight modules reach it not at all — so the apparatus is a parallel
development, like the construction theorem of
{bpref "lean_nixon_owen_reduction"}[the sparsity chapter]; the
module-by-module accounting appears in the correspondence chapter. What the
root theorem does take from these files is vocabulary: the coordinate-ideal
block of `FilteredInitialHeight.lean`, whose prime-chain height
bound the linear-form ideal height of the theorem above rests on.
