import Verso
import VersoManual
import VersoBlueprint
import BodyPinBlueprint.TeXPrelude
import BodyPinBlueprint.Bibliography

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option doc.verso true

/-
# The Split-Klein isotropic-difference ideal  (stub)

Paper §5, plus the Lean-only weight and initial-ideal apparatus.  Phase 4.
-/

#doc (Manual) "The Split-Klein isotropic-difference ideal" =>

*This chapter is a stub.* Its nodes are titled, tagged and mapped to the
correspondence table, but the mathematics is not written yet: each body is a
one-line placeholder naming the result it will state.

Section 5 of {Informal.citet "zheng2026"}[] translates the stress–codimension
inequality into commutative algebra. Twists are points of the six-dimensional
space $`k^3 \oplus k^3` carrying the Split–Klein quadratic form
$`q(\omega, b) = \omega \cdot b`, and for a graph $`F` the isotropic-difference
ideal $`I_F` is generated by one polynomial per edge, the condition
$`q(X_u - X_v) = 0` that the difference of the two endpoint twists is
isotropic. Theorem 1.3 computes the height of every minimal prime of $`I_F`
whose component meets the _distinct locus_, the open set of twist tuples with
$`X_u \ne X_v` for all $`u \ne v`: the height is $`|E_F|`, so after one twist
is fixed to zero every such component has dimension $`6(|V|-1) - |E_F|`. The
proof applies a Witt shear, chosen separately on each irreducible component,
under which the isotropic-difference equations become the linear equations of
the rigidity matrix over the generic fibre.

:::group "splitklein_spine"
The paper's algebraic argument.
:::

:::group "splitklein_infrastructure"
Weights and initial ideals, with no paper counterpart.
:::

:::definition "split_klein_form" (parent := "splitklein_spine") (tags := "paper, unwritten")
The Split–Klein quadratic form on twists $`X_v = (\omega_v, b_v)`. {Informal.citep "zheng2026" (kind := "equation") (index := "5.1")}[]
:::

:::definition "isotropic_difference_ideal" (parent := "splitklein_spine") (tags := "paper, unwritten") (uses := "split_klein_form")
The ideal $`I_F` generated by $`(\omega_u - \omega_v) \cdot (b_u - b_v)` over
the edges, and the open distinct locus. {Informal.citep "zheng2026" (kind := "equation") (index := "1.6 and 5.2")}[]
:::

:::lemma_ "witt_shear_componentwise" (parent := "splitklein_spine") (tags := "paper, unwritten") (uses := "isotropic_difference_ideal")
A componentwise Witt shear separating coincident coordinates on each
irreducible component that meets the distinct locus. {Informal.citep "zheng2026" (kind := "lemma") (index := "5.1")}[]
:::

:::lemma_ "polynomial_dimension_formula" (parent := "splitklein_spine") (tags := "paper, unwritten")
For a prime of a polynomial ring, $`\ht P + \trdeg = N`. {Informal.citep "zheng2026" (kind := "lemma") (index := "5.3")}[]
:::

:::theorem "isotropic_ideal_height" (parent := "splitklein_spine") (tags := "paper, unwritten") (uses := "witt_shear_componentwise, polynomial_dimension_formula")
Every minimal prime of $`I_F` whose component meets the distinct locus has
height $`|E_F|`; equivalently, after grounding, dimension $`6(|V| - 1) - |E_F|`.
{Informal.citep "zheng2026" (kind := "theorem") (index := "1.3")}[]
:::

:::corollary "ungrounded_variety" (parent := "splitklein_spine") (tags := "paper, unwritten") (uses := "isotropic_ideal_height")
The ungrounded isotropic-difference variety, obtained by restoring the scaling
orbit. {Informal.citep "zheng2026" (kind := "corollary") (index := "5.4")}[]
:::

:::lemma_ "lean_weight_apparatus" (parent := "splitklein_infrastructure") (tags := "lean-only, unwritten")
Provenance weights, initial ideals, weight components and replacement
identities: the formal apparatus standing behind the paper's componentwise
choice.
:::
